name: Pull Request

on:
  push:
    branches: 
      - '*'
      - '!main'
  pull_request:
    branches: 
      - '*'
      - '!main'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci

      - run: npm run test:unit
        env:
          REACT_APP_SHOW_FEATURE_1: true
          GATSBY_FEATURE_3: true
          OTHER_FEATURE_1: true
          REACT_APP_SHOW_FEATURE_2: false

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        
      - run: npm run build
      - run: npm publish --access public --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Auto merge dependabot PR's
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          github-token: ${{ secrets.AUTO_APPROVAL_PAT }}